/**
 * Infectious Disease Epidemiology, Herd Immunity & Levels of Prevention Learning Content
 * Authoritative medical content derived from Park, Gordis, and USMLE Step 1 / Step 2 CK Biostatistics.
 * Mapped to NMC CBME Competencies: CM3.1, CM3.2, CM3.3, CM4.1
 */

import { PhysiologyLessonModule } from "../physiology/cardiacCycleContent";

export const INFECTIOUS_DISEASE_PUBLIC_HEALTH_MODULE: PhysiologyLessonModule = {
  id: "comm-infectious-prevention",
  unitCode: "CM3.1",
  title: "Infectious Disease Dynamics: R0, Herd Immunity Threshold & the 5 Levels of Prevention",
  competencies: ["CM3.1", "CM3.2", "CM3.3", "CM4.1"],
  estimatedMinutes: 130,
  organ3dTarget: "GENERAL",
  markdownContent: `
# Infectious Disease Dynamics: R0, Herd Immunity Threshold & the 5 Levels of Prevention

Public Health interventions control the spread of communicable diseases through mathematical transmission modeling, vector control, surveillance, and systematic tiers of clinical prevention.

---

## 1. Transmission Dynamics & Herd Immunity Formulas

- **Basic Reproduction Number ($R_0$)**:
  - The average number of secondary infectious cases generated by a single primary case in a completely susceptible population.
  - $R_0 < 1.0 \\implies$ Disease will die out; $R_0 = 1.0 \\implies$ Disease becomes stable endemic; $R_0 > 1.0 \\implies$ Epidemic outbreak.
- **Herd Immunity Threshold ($HIT$)**:
  - The minimum proportion of the population that must possess immunity (via vaccination or prior natural infection) to prevent sustained epidemic transmission.
  $$HIT = 1 - \\frac{1}{R_0}$$
  - Examples:
    - **Measles ($R_0 \\approx 12\\text{–}18$)**: $HIT = 1 - 1/18 \\approx 94.4\\%$ (requires $\\ge 95\\%$ vaccine coverage).
    - **Smallpox ($R_0 \\approx 5\\text{–}7$)**: $HIT = 1 - 1/5 = 80\\%$.
    - **Influenza ($R_0 \\approx 1.5\\text{–}2$)**: $HIT = 1 - 1/2 = 50\\%$.
- **Attack Rate ($AR$) & Secondary Attack Rate ($SAR$)**:
  $$\\text{Attack Rate} = \\frac{\\text{Number of new cases exposed to risk}}{\\text{Total population at risk during outbreak}} \\times 100$$
  $$\\text{Secondary Attack Rate} = \\frac{\\text{Number of cases exposed to primary index case}}{\\text{Total susceptible household/close contacts}} \\times 100$$
  - *SAR is the primary epidemiological metric for evaluating the communicability / contagiousness of an infectious agent*.

---

## 2. The 5 Classical Levels of Prevention

| Level of Prevention | Stage of Disease Evolution | Primary Objective | Concrete Public Health & Clinical Examples |
| :--- | :--- | :--- | :--- |
| **Primordial Prevention** | **Underlying social, environmental & economic determinants** (precedes emergence of risk factors) | Inhibits the emergence of lifestyle and environmental risk factors in the entire community. | • National public policies banning trans fats in foods.<br>• Urban planning for pedestrian walking/cycling tracks.<br>• Anti-tobacco legislation and youth sports subsidies. |
| **Primary Prevention** | **Pre-pathogenesis period** (Risk factors present, but biological disease has NOT initiated) | Prevents disease onset in susceptible individuals via specific protection and health promotion. | • **Active Immunization / Childhood Vaccines** (MMR, BCG, Polio).<br>• Condom distribution for STI/HIV prevention.<br>• Water fluoridation; Folic acid supplementation in pregnancy. |
| **Secondary Prevention** | **Early pathogenesis / Asymptomatic phase** (Biological disease is present, but subclinical) | **Early diagnosis and prompt treatment** to halt disease progression and prevent irreversible complications. | • **Screening Mammography for Breast Cancer**.<br>• **Pap Smear for Cervical Cancer**.<br>• Routine Blood Pressure screening for Hypertension.<br>• Colonoscopy / Fecal Occult Blood for Colorectal Cancer. |
| **Tertiary Prevention** | **Late symptomatic / Established disease stage** | **Disability limitation and physical/social rehabilitation** to restore maximum functional capacity. | • Physical and occupational therapy post-ischemic stroke.<br>• Cardiac rehabilitation after myocardial infarction.<br>• Glycemic management to prevent amputation in diabetic foot ulcers. |
| **Quaternary Prevention** | **Patient at risk of over-medicalization** | Protects patients from unnecessary diagnostic workups, medical harm, and iatrogenic interventions. | • Deprescribing unnecessary polypharmacy in the elderly.<br>• Avoiding redundant CT scans for uncomplicated tension headaches. |
`,
  clinicalVignettes: [
    {
      scenario: "During an outbreak investigation of a novel respiratory pathogen, epidemiological modeling establishes a Basic Reproduction Number (R0) of 4.0 in a fully susceptible population.",
      question: "What is the minimum Herd Immunity Threshold (HIT) percentage of the population that must be effectively immunized to halt transmission of this pathogen?",
      options: [
        "75%",
        "50%",
        "90%",
        "25%"
      ],
      correctAnswerIndex: 0,
      explanation: "The Herd Immunity Threshold is calculated using the formula: HIT = 1 - (1 / R0). Substituting R0 = 4.0 yields: HIT = 1 - (1 / 4) = 1 - 0.25 = 0.75 (75%). Thus, at least 75% of the population must possess protective immunity to stop epidemic transmission."
    }
  ]
};
