apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: mediverse-backend-pdb
  namespace: mediverse
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mediverse-backend
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: mediverse-frontend-pdb
  namespace: mediverse
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mediverse-frontend
