apiVersion: v1
kind: Secret
metadata:
  name: mediverse-secrets
  namespace: mediverse
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: "mediverse_user"
  SPRING_DATASOURCE_PASSWORD: "change_me_in_vault"
  JWT_SECRET: "change_me_in_vault_must_be_256_bits_long_for_hs512_security"
  GEMINI_API_KEY: "change_me_in_vault"
