/**
 * Postgraduate Advanced Physical Medicine & Rehabilitation Curriculum Index (PG-611)
 * Aggregates all 4 postgraduate PM&R & neurotrauma modules.
 */

import { SPINAL_CORD_INJURY_ASIA_AUTONOMIC_DYSREFLEXIA_MODULE } from "./spinalCordInjuryAsiaAutonomicDysreflexiaContent";
import { TRAUMATIC_BRAIN_INJURY_RANCHO_CONCUSSION_MODULE } from "./traumaticBrainInjuryRanchoConcussionContent";
import { STROKE_SPASTICITY_BOTOX_INTRATHECAL_BACLOFEN_MODULE } from "./strokeSpasticityBotoxIntrathecalBaclofenContent";
import { PEDIATRIC_CEREBRAL_PALSY_GAIT_PROSTHETICS_MODULE } from "./pediatricCerebralPalsyGaitProstheticsContent";

export const PG11_MODULES = [
  SPINAL_CORD_INJURY_ASIA_AUTONOMIC_DYSREFLEXIA_MODULE,
  TRAUMATIC_BRAIN_INJURY_RANCHO_CONCUSSION_MODULE,
  STROKE_SPASTICITY_BOTOX_INTRATHECAL_BACLOFEN_MODULE,
  PEDIATRIC_CEREBRAL_PALSY_GAIT_PROSTHETICS_MODULE
];

export {
  SPINAL_CORD_INJURY_ASIA_AUTONOMIC_DYSREFLEXIA_MODULE,
  TRAUMATIC_BRAIN_INJURY_RANCHO_CONCUSSION_MODULE,
  STROKE_SPASTICITY_BOTOX_INTRATHECAL_BACLOFEN_MODULE,
  PEDIATRIC_CEREBRAL_PALSY_GAIT_PROSTHETICS_MODULE
};
