-- V201: Seed Rich Tier 1 Curriculum Content for Public Health (MPH/MHA) and Veterinary Medicine (BVSc & AH / MVSc)

-- 1. Ensure all concepts across Public Health and Veterinary have associated Lessons
INSERT INTO lessons (id, concept_id, title, status, version, created_at)
SELECT 
    gen_random_uuid(),
    c.id,
    c.title,
    'PUBLISHED',
    1,
    CURRENT_TIMESTAMP
FROM concepts c
WHERE NOT EXISTS (SELECT 1 FROM lessons l WHERE l.concept_id = c.id)
ON CONFLICT (id) DO NOTHING;

-- 2. Seed Rich Clinical Content Blocks for Public Health Core Topics
-- Public Health: SEIR Epidemic Modeling & Outbreak Dynamics (CBME PH-EPI1)
INSERT INTO content_blocks (id, lesson_id, type, order_index, status, metadata)
SELECT 
    '80000000-0000-0000-0009-000000000001',
    l.id,
    'EXPLANATION',
    1,
    'PUBLISHED',
    jsonb_build_object(
        'title', 'Infectious Disease Epidemiology: SEIR Compartmental Modeling, R0 Transmission Dynamics & Epidemic Curves',
        'text', '# Infectious Disease Epidemiology & Mathematical Modeling (CBME PH-EPI1)\n\n## 1. The SEIR Compartmental Framework\nThe **SEIR Model** divides the population into four distinct dynamic epidemiological states:\n\n```mermaid\ngraph LR\n  S[Susceptible (S)] -->|Beta * S * I / N| E[Exposed / Latent (E)]\n  E -->|Sigma * E| I[Infectious (I)]\n  I -->|Gamma * I| R[Recovered / Immune (R)]\n```\n\n### Key Mathematical Parameters:\n1. **Basic Reproduction Number ($R_0$)**: Average number of secondary infectious cases generated by a single index case in a completely susceptible population:\n   $$ R_0 = \\frac{\\beta}{\\gamma} \\times c $$\n   where $\\beta$ = transmission probability per contact, $\\gamma$ = recovery rate ($1/\\text{infectious period}$), and $c$ = contact rate.\n2. **Effective Reproduction Number ($R_t$)**: Real-time transmission rate accounting for population immunity and public health interventions ($R_t = R_0 \\times S/N$).\n3. **Herd Immunity Threshold ($I_c$)**: Proportion of the population that must be immune to achieve epidemic decline ($R_t < 1$):\n   $$ I_c = 1 - \\frac{1}{R_0} $$\n\n:::pearl\n**Epidemic Curve Interpretation**:\n- **Point Source Outbreak**: Sharp unimodal peak with steep upward slope and gradual decline, where all cases fall within a single incubation period (e.g. food poisoning from contaminated banquet).\n- **Continuous Common Source**: Plateau-shaped epidemic curve spanning multiple incubation periods without distinct peak (e.g. contaminated municipal water supply).\n- **Propagated (Person-to-Person) Outbreak**: Series of progressively taller waves separated by approximately one incubation period (e.g. Measles, Influenza, SARS-CoV-2).\n:::'
    )
FROM concepts c
JOIN lessons l ON l.concept_id = c.id
WHERE c.title ILIKE '%Epidemiology%' OR c.title ILIKE '%Outbreak%' OR c.title ILIKE '%Public Health%'
LIMIT 1
ON CONFLICT (id) DO UPDATE SET metadata = EXCLUDED.metadata, status = 'PUBLISHED';

-- Public Health Clinical MCQ Quiz
INSERT INTO content_blocks (id, lesson_id, type, order_index, status, metadata)
SELECT 
    '80000000-0000-0000-0009-000000000002',
    l.id,
    'QUIZ',
    2,
    'PUBLISHED',
    jsonb_build_object(
        'title', 'Epidemic Modeling & Outbreak Investigation Clinical Quiz',
        'questions', jsonb_build_array(
            jsonb_build_object(
                'question', 'If a novel respiratory viral pathogen has a Basic Reproduction Number (R0) of 4.0 in an immunologically naive population, what minimum percentage of the population must be effectively immunized to halt community transmission via herd immunity?',
                'options', jsonb_build_array(
                    '75% (Herd Immunity Threshold = 1 - 1/4 = 0.75)',
                    '60%',
                    '50%',
                    '90%'
                ),
                'correctIndex', 0,
                'explanation', 'The Herd Immunity Threshold equation is Ic = 1 - (1/R0). For R0 = 4.0: Ic = 1 - (1/4.0) = 1 - 0.25 = 0.75 (or 75%). Thus, 75% of the population must possess sterilizing immunity to bring the effective reproduction number Rt below 1.0.',
                'clinicalPearl', 'If vaccine efficacy against transmission (VE) is less than 100%, the required vaccination coverage Vc = Ic / VE.'
            )
        )
    )
FROM concepts c
JOIN lessons l ON l.concept_id = c.id
WHERE c.title ILIKE '%Epidemiology%' OR c.title ILIKE '%Outbreak%' OR c.title ILIKE '%Public Health%'
LIMIT 1
ON CONFLICT (id) DO UPDATE SET metadata = EXCLUDED.metadata, status = 'PUBLISHED';

-- 3. Seed Rich Clinical Content Blocks for Veterinary Medicine Core Topics
-- Veterinary: Ruminant Forestomach Fermentation & Zoonoses (VCI CBME VET-RUM1)
INSERT INTO content_blocks (id, lesson_id, type, order_index, status, metadata)
SELECT 
    '90000000-0000-0000-0009-000000000001',
    l.id,
    'EXPLANATION',
    1,
    'PUBLISHED',
    jsonb_build_object(
        'title', 'Ruminant Forestomach Physiology, Volatile Fatty Acid Fermentation & Zoonotic Spillover Sentinel',
        'text', '# Ruminant Forestomach Physiology & Zoonotic Disease Surveillance (VCI CBME VET-RUM1)\n\n## 1. Anatomical & Physiological Forestomach Compartments\nThe ruminant stomach consists of three non-glandular forestomachs and one glandular stomach:\n\n1. **Rumen (Paunch)**: Largest anaerobic fermentation vat (pH 5.8–6.8); houses billions of cellulolytic bacteria, protozoa, and anaerobic fungi.\n2. **Reticulum (Honeycomb)**: Traps dense foreign metal objects (Hardware Disease / Traumatic Reticuloperitonitis); initiates primary regurgitation contractions (rumination).\n3. **Omasum (Manyplies / Bible)**: Laminar muscular leaves absorb 60–70% of water, electrolytes, and residual bicarbonate from ingesta.\n4. **Abomasum (True Stomach)**: Glandular stomach secreting HCl and pepsin (pH 2.0–3.0); digests microbial protein and bypass nutrients.\n\n### Microbial Volatile Fatty Acids (VFAs):\n- **Acetate ($CH_3COO^-$)**: 60–70% of total VFAs; primary precursor for milk fat synthesis in the mammary gland.\n- **Propionate ($CH_3CH_2COO^-$)**: 15–20% of VFAs; **sole glucogenic VFA** converted to glucose via hepatic gluconeogenesis.\n- **Butyrate ($CH_3(CH_2)_2COO^-$)**: 10–15% of VFAs; converted to $\\beta$-hydroxybutyrate (ketone bodies) in rumen epithelium to provide mucosal energy.\n\n:::pearl\n**Veterinary Emergency Surgical Pearl (Acute Ruminal Bloat / Tympany)**:\n- **Pathophysiology**: Failure of eructation leading to severe distension of the dorsal rumen sac, compressing the diaphragm and caudal vena cava, causing asphyxiation.\n- **Emergency Trocarization**: Insertion of a large-bore trocar directly into the center of the **left paralumbar fossa** (equidistant between the last rib, lumbar transverse processes, and coxal tuber).\n:::\n\n## 2. One Health Zoonoses: Anthrax Sentinel Protocol\n- In cases of sudden unexpected livestock death with dark, uncoagulated tarry blood exuding from natural orifices and marked absence of rigor mortis:\n- **STRICT PROTOCOL**: **NEVER OPEN OR NECROPSY THE CARCASS**. Exposure of vegetative *Bacillus anthracis* to atmospheric oxygen induces lethal, resistant sporulation that contaminates pasture for decades.'
    )
FROM concepts c
JOIN lessons l ON l.concept_id = c.id
WHERE c.title ILIKE '%Ruminant%' OR c.title ILIKE '%Veterinary%' OR c.title ILIKE '%Anatomy%'
LIMIT 1
ON CONFLICT (id) DO UPDATE SET metadata = EXCLUDED.metadata, status = 'PUBLISHED';

-- Veterinary Flashcards Mastery Deck
INSERT INTO content_blocks (id, lesson_id, type, order_index, status, metadata)
SELECT 
    '90000000-0000-0000-0009-000000000002',
    l.id,
    'FLASHCARD_SET',
    2,
    'PUBLISHED',
    jsonb_build_object(
        'title', 'Ruminant Physiology, Equine Colic & Zoonoses Veterinary Deck',
        'cards', jsonb_build_array(
            jsonb_build_object(
                'front', 'Which Volatile Fatty Acid (VFA) produced during ruminal fermentation serves as the primary substrate for hepatic gluconeogenesis in dairy cattle?',
                'back', 'Propionate (Propionic acid).',
                'cloze', 'The only glucogenic volatile fatty acid in ruminants is {{c1::Propionate}}.',
                'difficulty', 'Core'
            ),
            jsonb_build_object(
                'front', 'What is the precise anatomical site for emergency trocarization in a dairy cow with acute frothy/free-gas ruminal bloat?',
                'back', 'Center of the left paralumbar fossa (bounded by the last rib, lumbar transverse processes, and tuber coxae).',
                'cloze', 'Emergency ruminal decompression is performed at the {{c1::left paralumbar fossa}}.',
                'difficulty', 'High-Yield'
            ),
            jsonb_build_object(
                'front', 'Why is post-mortem necropsy strictly prohibited when Anthrax (Bacillus anthracis) is suspected in a dead animal?',
                'back', 'Atmospheric oxygen triggers vegetative cells to form extremely resilient, long-lived spores that contaminate soil and pastures for decades.',
                'cloze', 'Opening an anthrax carcass is forbidden because oxygen exposure induces {{c1::bacterial sporulation}}.',
                'difficulty', 'High-Yield'
            )
        )
    )
FROM concepts c
JOIN lessons l ON l.concept_id = c.id
WHERE c.title ILIKE '%Ruminant%' OR c.title ILIKE '%Veterinary%' OR c.title ILIKE '%Anatomy%'
LIMIT 1
ON CONFLICT (id) DO UPDATE SET metadata = EXCLUDED.metadata, status = 'PUBLISHED';
