import React from 'react';
import type { Metadata } from 'next';
import Link from 'next/link';
import {
  ArrowLeft,
  Activity,
  Brain,
  Layers,
  Zap,
  ShieldAlert,
  BarChart3
} from 'lucide-react';
import EEGNeurophysiologySimulator from '@/components/simulators/EEGNeurophysiologySimulator';

export const metadata: Metadata = {
  title: 'Clinical Neurophysiology & Quantitative EEG (qEEG) Workstation | Mediverse',
  description:
    'Comprehensive 16-channel electrophysiological tracing, International 10-20 montages, physiological frequency bands, epileptiform discharges, and FFT quantitative spectral analytics.',
};

export default function EEGNeurophysiologyPage() {
  return (
    <div className="min-h-screen bg-slate-950 text-slate-100 p-4 md:p-8">
      <div className="max-w-7xl mx-auto space-y-6">
        {/* Top Navigation & Status Badges */}
        <div className="flex flex-wrap items-center justify-between gap-4">
          <Link
            href="/simulators"
            className="inline-flex items-center gap-2 text-xs font-semibold text-slate-400 hover:text-white transition bg-slate-900 border border-slate-800 px-3 py-1.5 rounded-lg"
          >
            <ArrowLeft className="w-4 h-4" />
            Back to Clinical Simulators
          </Link>

          <div className="flex items-center gap-2 text-xs">
            <span className="px-2.5 py-1 rounded-full bg-cyan-500/10 text-cyan-400 border border-cyan-500/20 font-bold">
              CLINICAL NEUROPHYSIOLOGY
            </span>
            <span className="px-2.5 py-1 rounded-full bg-violet-500/10 text-violet-400 border border-violet-500/20 font-bold">
              ACNS 10-20 GUIDELINES
            </span>
            <span className="px-2.5 py-1 rounded-full bg-amber-500/10 text-amber-400 border border-amber-500/20 font-bold">
              qEEG &amp; aEEG ANALYTICS
            </span>
          </div>
        </div>

        {/* Main Workstation Interactive Component */}
        <EEGNeurophysiologySimulator />

        {/* High-Yield Board Review & Curriculum Cards */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 pt-4">
          {/* Card 1: 10-20 System, Montages & Normal Rhythms */}
          <div className="bg-slate-900/60 border border-slate-800 rounded-2xl p-6 space-y-4">
            <div className="flex items-center gap-2.5 text-cyan-400">
              <Layers className="w-5 h-5" />
              <h2 className="text-sm font-bold uppercase tracking-wider text-white">
                10-20 System &amp; Normal Rhythms
              </h2>
            </div>
            <ul className="space-y-3 text-xs text-slate-300 leading-relaxed">
              <li className="p-2.5 rounded-lg bg-slate-950/70 border border-slate-800/80">
                <strong className="text-cyan-300 font-semibold block mb-0.5">
                  Montage Principles &amp; Common Mode Rejection:
                </strong>
                Longitudinal bipolar (&quot;Double Banana&quot;) records voltage differences along anteroposterior chains. Localizes focal epileptogenic spikes by finding Phase Reversal (pointing toward the electronegative focus). Referential montages record against an inactive average or linked earlobes (A1+A2), optimizing absolute amplitude estimation.
              </li>
              <li className="p-2.5 rounded-lg bg-slate-950/70 border border-slate-800/80">
                <strong className="text-cyan-300 font-semibold block mb-0.5">
                  Posterior Dominant Rhythm (PDR) &amp; Reactivity:
                </strong>
                Normal adult awake background is an 8.5–12 Hz sinusoidal alpha rhythm maximal over bilateral occipital electrodes (O1, O2). Demonstrates the classic Berger effect: immediate attenuation and desynchronization upon eye opening, promptly returning with eye closure.
              </li>
              <li className="p-2.5 rounded-lg bg-slate-950/70 border border-slate-800/80">
                <strong className="text-cyan-300 font-semibold block mb-0.5">
                  Sleep Stage N2 Architecture:
                </strong>
                Characterized by 12–14 Hz waxing-and-waning sinusoidal Sleep Spindles generated by thalamic reticular burst-firing (maximal at vertex/Cz, C3, C4) and high-amplitude biphasic K-complexes (&gt;100 µV, &gt;0.5s duration) fronto-centrally.
              </li>
            </ul>
          </div>

          {/* Card 2: Epileptiform Discharges & Encephalopathy */}
          <div className="bg-slate-900/60 border border-slate-800 rounded-2xl p-6 space-y-4">
            <div className="flex items-center gap-2.5 text-violet-400">
              <Zap className="w-5 h-5" />
              <h2 className="text-sm font-bold uppercase tracking-wider text-white">
                Epileptiform &amp; Encephalopathic Signatures
              </h2>
            </div>
            <ul className="space-y-3 text-xs text-slate-300 leading-relaxed">
              <li className="p-2.5 rounded-lg bg-slate-950/70 border border-slate-800/80">
                <strong className="text-violet-300 font-semibold block mb-0.5">
                  3 Hz Absence Spike-and-Wave:
                </strong>
                Pathognomonic for Childhood Absence Epilepsy. Generalized, symmetric 3 Hz spike-and-slow-wave paroxysms with sudden onset and abrupt offset, reliably triggered by 3 minutes of hyperventilation. First-line therapy is Ethosuximide (T-type Ca2+ channel inhibitor); avoid sodium channel blockers.
              </li>
              <li className="p-2.5 rounded-lg bg-slate-950/70 border border-slate-800/80">
                <strong className="text-violet-300 font-semibold block mb-0.5">
                  PLEDs / LPDs (Herpes Simplex Encephalitis):
                </strong>
                Periodic Lateralized Epileptiform Discharges recurring at 1–2 Hz over the temporal lobe (F7-T3-T5). Characteristic of acute necrotizing HSV-1 encephalitis. Prompts immediate empiric IV Acyclovir (10 mg/kg q8h) and anti-seizure coverage without awaiting CSF PCR.
              </li>
              <li className="p-2.5 rounded-lg bg-slate-950/70 border border-slate-800/80">
                <strong className="text-violet-300 font-semibold block mb-0.5">
                  Triphasic Waves (Hepatic / Metabolic):
                </strong>
                Generalized bilateral synchronous 1.5–2.2 Hz complexes with 3 distinct phases and an anterior-to-posterior (AP) phase lag (25–140 ms). Characteristic of hyperammonemia, Grade 3–4 hepatic encephalopathy, or uremia.
              </li>
            </ul>
          </div>

          {/* Card 3: Quantitative EEG (qEEG) & Neuro-ICU Monitoring */}
          <div className="bg-slate-900/60 border border-slate-800 rounded-2xl p-6 space-y-4">
            <div className="flex items-center gap-2.5 text-amber-400">
              <BarChart3 className="w-5 h-5" />
              <h2 className="text-sm font-bold uppercase tracking-wider text-white">
                qEEG &amp; Neurocritical Monitoring
              </h2>
            </div>
            <ul className="space-y-3 text-xs text-slate-300 leading-relaxed">
              <li className="p-2.5 rounded-lg bg-slate-950/70 border border-slate-800/80">
                <strong className="text-amber-300 font-semibold block mb-0.5">
                  Burst Suppression Ratio (BSR %):
                </strong>
                Epochs of high-voltage polymorphic activity alternating with isoelectric suppression (&lt;5 µV). Target therapeutic BSR for refractory status epilepticus or intracranial hypertension is 70–85% using continuous IV propofol, midazolam, or pentobarbital infusions.
              </li>
              <li className="p-2.5 rounded-lg bg-slate-950/70 border border-slate-800/80">
                <strong className="text-amber-300 font-semibold block mb-0.5">
                  Alpha-Delta Ratio (ADR) &amp; Ischemia Detection:
                </strong>
                qEEG spectral trend monitoring for delayed cerebral ischemia (DCI) following aneurysmal subarachnoid hemorrhage (aSAH). A progressive drop in the Alpha-Delta Ratio (&lt;0.8) or Relative Alpha Variability precedes clinical neurological deterioration by 24–48 hours.
              </li>
              <li className="p-2.5 rounded-lg bg-slate-950/70 border border-slate-800/80">
                <strong className="text-amber-300 font-semibold block mb-0.5">
                  Electrocerebral Inactivity (Brain Death Criteria):
                </strong>
                Strict ACNS criteria require confirmation of no electrocerebral activity &gt;2 µV at high sensitivity (2 µV/mm) for at least 30 minutes with electrode distance &gt;10 cm, serving as an ancillary test alongside clinical apnea testing.
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  );
}
