/**
 * Emergency Medicine: Emergency Toxicology & Clinical Toxidromes
 * Authoritative medical content derived from Goldfrank's Toxicologic Emergencies (11th ed.), Tintinalli.
 * Mapped to NMC CBME Competencies: EM1.5, EM1.6, MD35.3, AN22.3
 */

import { PhysiologyLessonModule } from "../physiology/cardiacCycleContent";

export const EMERGENCY_TOXICOLOGY_TOXIDROMES_MODULE: PhysiologyLessonModule = {
  id: "emergency-adv-toxicology-toxidromes",
  unitCode: "EM5.1",
  title: "Emergency Toxicology: Clinical Toxidromes (Cholinergic, Anticholinergic, Opioid, Sympathomimetic) & Antidotes",
  competencies: ["EM1.5", "EM1.6", "MD35.3", "AN22.3"],
  estimatedMinutes: 150,
  organ3dTarget: "BRAIN",
  markdownContent: `
# Emergency Toxicology & Clinical Toxidromes

A toxidrome is a constellation of physical signs and vital parameter abnormalities that characterizes a specific toxic class.

---

## 1. Master Toxidrome Differential Matrix

$$\\begin{array}{lcccc}
\\hline
\\textbf{Toxidrome} & \\textbf{Pupil Size} & \\textbf{Vital Signs} & \\textbf{Skin / Secretions} & \\textbf{Specific Antidote / Management} \\\\
\\hline
\\textbf{Anticholinergic} & \\mathbf{\\text{Mydriasis (Dilated)}} & \\mathbf{\\uparrow\\text{HR, }\\uparrow\\text{BP, }\\uparrow\\text{Temp}} & \\mathbf{\\text{Dry, Flushed (\"Red as beet\")}} & \\mathbf{\\text{Physostigmine (AChE Inhibitor)}} \\\\
\\text{(Atropine, TCAs, Benadryl)} & \\text{(Non-reactive)} & \\text{(\"Hot as a hare\")} & \\mathbf{\\text{\"Dry as a bone, Mad as hatter\"}} & \\text{(Caution: contraindicated in TCA QRS)} \\\\
\\textbf{Cholinergic} & \\mathbf{\\text{Miosis (Pinpoint)}} & \\mathbf{\\downarrow\\text{HR, }\\downarrow\\text{BP, }\\uparrow\\text{RR}} & \\mathbf{\\text{Profuse SLUDGE / DUMBELS}} & \\mathbf{\\text{Atropine (muscarinic) +}} \\\\
\\text{(Organophosphates, Nerve agents)} & & & \\text{(Diaphoresis, Salivation, Bronchorrhea)} & \\mathbf{\\text{Pralidoxime 2-PAM (nicotinic)}} \\\\
\\textbf{Opioid} & \\mathbf{\\text{Pinpoint Miosis}} & \\mathbf{\\downarrow\\text{RR (<8/min), }\\downarrow\\text{HR, }\\downarrow\\text{BP}} & \\text{Normal / Cool} & \\mathbf{\\text{Naloxone (Opioid Antagonist)}} \\\\
\\text{(Heroin, Fentanyl, Morphine)} & & \\mathbf{\\text{Hypoventilation / Coma}} & & \\text{(Titrate to restore respiratory drive)} \\\\
\\textbf{Sympathomimetic} & \\mathbf{\\text{Mydriasis (Dilated)}} & \\mathbf{\\uparrow\\uparrow\\text{HR, }\\uparrow\\uparrow\\text{BP, }\\uparrow\\uparrow\\text{Temp}} & \\mathbf{\\text{PROFUSE SWEATING (Diaphoretic!)}} & \\mathbf{\\text{Benzodiazepines (Lorazepam)}} \\\\
\\text{(Cocaine, Amphetamines)} & \\text{(Reactive)} & \\text{Agitation, Tremor, Seizures} & \\text{(Differentiates from Anticholinergic)} & \\text{(Avoid beta-blockers: unopposed }\\alpha\\text{)} \\\\
\\hline
\\end{array}$$

---

## 2. High-Yield Poisonings: TCAs & Acetaminophen

1. **Tricyclic Antidepressant (TCA) Overdose (Amitriptyline)**:
   - **Pathophysiology**: Fast sodium channel blockade in cardiac His-Purkinje tissue $\rightarrow$ QRS prolongation ($>100\\text{ ms}$ predicts seizures, $>160\\text{ ms}$ predicts ventricular arrhythmias), right axis deviation of terminal $40\\text{ ms}$ (terminal R wave in aVR $>3\\text{ mm}$).
   - **Emergency Antidote**: **Intravenous Sodium Bicarbonate ($\\text{NaHCO}_3$, $1-2\\text{ mEq/kg}$ bolus)** to overcome sodium channel blockade by flooding channels with extracellular $\\text{Na}^+$ and alkalinizing serum pH ($7.50-7.55$).

2. **Acetaminophen (Paracetamol) Poisoning**:
   - **Toxic Metabolite**: **NAPQI** (N-acetyl-p-benzoquinone imine) generated by CYP2E1 exceeds glutathione stores $\rightarrow$ binds hepatocyte proteins $\rightarrow$ centrilobular liver necrosis.
   - **Management**: Plot 4-hour post-ingestion serum level on the **Rumack-Matthew Nomogram**. Administer **N-Acetylcysteine (NAC)** intravenously or orally to restore glutathione stores (nearly $100\\%$ effective if started within 8 hours).
`,
  clinicalVignettes: [
    {
      scenario: "A 23-year-old female is brought to the emergency department after ingesting a large handful of amitriptyline tablets in a suicide attempt 90 minutes ago. On arrival, she is obtunded with a GCS of 8. Vital signs: BP 82/46 mmHg, HR 134 bpm, RR 14/min, Temp 38.2°C. Pupils are 7 mm and sluggishly reactive. Physical exam shows dry mucous membranes, absent bowel sounds, and axillary dryness. An urgent 12-lead ECG demonstrates sinus tachycardia with a QRS duration of 148 ms and a prominent terminal R wave of 4.5 mm in lead aVR.",
      question: "Which of the following is the most appropriate and immediate pharmacotherapy to prevent fatal ventricular dysrhythmias?",
      options: [
        "Intravenous Sodium Bicarbonate (NaHCO3) boluses titrated to achieve a serum pH of 7.50 - 7.55",
        "Intravenous Physostigmine 2 mg slow push",
        "Intravenous Amiodarone 300 mg bolus",
        "Intravenous Flumazenil 0.2 mg slow push"
      ],
      correctAnswerIndex: 0,
      explanation: "This patient exhibits life-threatening Tricyclic Antidepressant (TCA) toxicity characterized by anticholinergic features (mydriasis, dry skin, hyperthermia, tachycardia) combined with cardiotoxicity from cardiac fast sodium channel blockade. The hallmark ECG findings are QRS widening (>100 ms predicts seizures, >160 ms predicts ventricular arrhythmias) and a prominent terminal R wave in aVR (>3 mm). The immediate life-saving treatment is Intravenous Sodium Bicarbonate (NaHCO3). Sodium bicarbonate works by: (1) providing a high sodium load to overcome competitive sodium channel blockade, and (2) alkalinizing the serum (target pH 7.50-7.55), which neutralizes the drug into an uncharged form that dissociates from the sodium channel receptor. Physostigmine is contraindicated in TCA overdose as it can precipitate asystolic cardiac arrest."
    }
  ]
};
